#!/bin/sh

# alias cutter=$HOME/src/cardboard/build/cutter/cutter

mod=super

cutter config mouse_mod $mod
# cutter config gap "int"
cutter config gap 5
cutter config focus_color 210 98 115 125
# cutter config focus_color "255,0,0,0"

cutter bind $mod+shift+e quit
cutter bind $mod+q close

cutter bind $mod+return exec alacritty
cutter bind $mod+d exec kickoff

cutter bind $mod+left focus left
cutter bind $mod+right focus right
cutter bind $mod+up focus up
cutter bind $mod+down focus down

cutter bind $mod+h focus left
cutter bind $mod+l focus right
cutter bind $mod+k focus up
cutter bind $mod+j focus down

cutter bind $mod+shift+left move -10 0
cutter bind $mod+shift+right move 10 0
cutter bind $mod+shift+up move 0 -10
cutter bind $mod+shift+down move 0 10

for i in $(seq 1 6); do
	cutter bind $mod+$i workspace switch $((i - 1))
	cutter bind $mod+shift+$i workspace move $((i - 1))
done

cutter bind $mod+shift+space toggle_floating
cutter bind $mod+shift+p pop_from_column
cutter bind $mod+shift+i insert_into_column
cutter bind $mod+tab focus cycle

# cutter exec toolbox run swaybg -i ~/wallpapers/autobahn.png
cutter exec eww daemon &
cutter exec eww open bar &
cutter exec fcitx5 -d &
cutter exec mako &
cutter exec clash-verge &
cutter exec swww init &
# cutter exec pokemon -w &
