#!/bin/sh

DERV=$(nix derivation show "$@" | jq -rs '.[0]|to_entries[].value.outputs.out.path')
if [ -d "$DERV" ]; then
    yazi "$DERV"
else
    nix derivation show "$@" | jq -s '.[0]|to_entries[].value.outputs'
fi
