#!/bin/sh
# use keyboard to move mause

riverctl declare-mode dotool
riverctl map normal Super F12 enter-mode dotool
riverctl map dotool Super F12 enter-mode normal

riverctl map dotool Super K spawn 'ydotool mousemove -x 0 -y -100'
riverctl map dotool Super J spawn 'ydotool mousemove -x 0 -y 100'
riverctl map dotool Super H spawn 'ydotool mousemove -x -100 -y 0'
riverctl map dotool Super L spawn 'ydotool mousemove -x 100 -y 0'

riverctl map dotool Super+Shift K spawn 'ydotool mousemove -x 0 -y -10'
riverctl map dotool Super+Shift J spawn 'ydotool mousemove -x 0 -y 10'
riverctl map dotool Super+Shift H spawn 'ydotool mousemove -x -10 -y 0'
riverctl map dotool Super+Shift L spawn 'ydotool mousemove -x 10 -y 0'

riverctl map dotool Super Space spawn 'ydotool click 0xC0'
riverctl map dotool Super+Shift Space spawn 'ydotool click 0xC1'

# doas ydotoold -o 1000:100
