#!/bin/sh
set -e
APPID="float-slurp-term"
# slurp | river-slurp-term

IFS=', x' read -r x y w h
riverctl rule-add -app-id "$APPID" position "$x" "$y"
riverctl rule-add -app-id "$APPID" dimensions "$w" "$h"
alacritty --class="$APPID" &
riverctl rule-add -app-id "$APPID" position
riverctl rule-add -app-id "$APPID" dimensions
