#!/bin/sh

FIFO="$XDG_RUNTIME_DIR/sandbar"
[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"

while cat "$FIFO"; do :; done | sandbar \
	-font "Maple Mono SC NF" \
	-active-fg-color "#83cbac" \
	-active-bg-color "#223e36" \
	-inactive-fg-color "#223e36" \
	-inactive-bg-color "#83cbac" \
	-urgent-fg-color "#223e36" \
	-urgent-bg-color "#ce5777" \
	-title-fg-color "#83cbac" \
	-title-bg-color "#223e36"
